import "./globals.css";
import stars from "@/public/assets/background-stars.svg"
import { Antonio, League_Spartan} from "next/font/google"; 

const antonio = Antonio({
  subsets: ["latin"], 
  weight: "400"
})

const leagueSpartan = League_Spartan({
  subsets: ["latin"], 
  weight: "400"
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{backgroundImage: `url(${stars})`}} className={`${antonio.className} ${leagueSpartan.className}`}>
        {children}
      </body>
    </html>
  );
}
